import {useEffect,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {api} from './api';

type Props={run:(work:()=>Promise<void>)=>Promise<void>;reload:()=>void};
export function Members({members,devices,run,reload}:{members:any[];devices:any[]}&Props){
 const[pair,setPair]=useState<any>(null),[clock,setClock]=useState(Date.now()),[address,setAddress]=useState(''),[candidates,setCandidates]=useState<string[]>([]);
 useEffect(()=>{api('/pairing/address').then(v=>{setAddress(v.addresses[0]??v.candidates[0]??'');setCandidates(v.candidates)}).catch(()=>{})},[]);
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(id)},[]);
 const generate=(id:string)=>run(async()=>{setPair(await api('/members/'+id+'/pairing','POST'))});
 return <><section><h2>家庭连接地址</h2><p>未开通远程时，二维码使用此地址，iPhone 无需手填。请选择手机可达的家庭网络地址。</p><input aria-label="家庭 HTTPS 地址" list="lan-addresses" type="url" value={address} onChange={e=>setAddress(e.target.value)}/><datalist id="lan-addresses">{candidates.map(url=><option key={url} value={url}/>)}</datalist><button onClick={()=>run(async()=>{await api('/pairing/address','PUT',{url:address});setPair(null)})}>保存家庭地址</button></section><section><h2>家庭成员</h2><form onSubmit={e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name');run(async()=>{await api('/members','POST',{name});reload()})}}><label>新成员名称<input name="name" required maxLength={100}/></label><button className="primary">创建成员</button></form>{members.map(m=><div className="row" key={m.id}><span>{m.name}</span><button onClick={()=>generate(m.id)}>生成配对二维码</button></div>)}</section>{pair&&<section><h2>iPhone 扫码配对</h2>{pair.expires_at*1000>clock?<><QRCodeSVG value={JSON.stringify(pair.code)} size={320} level="M" marginSize={4}/><p>{pair.mode==='remote'?'支持外网首次扫码，自动建立纯直连':'请让 iPhone 与家庭服务器处于可互通的局域网'}</p><p>剩余 {Math.ceil((pair.expires_at*1000-clock)/1000)} 秒；二维码仅供该成员使用。</p></>:<p>二维码已过期，请重新生成。</p>}<button onClick={()=>setPair(null)}>关闭二维码</button></section>}<section><h2>我的设备</h2>{devices.map(d=><div className="row" key={d.id}><span>{d.name}</span><span>{d.revoked?'已撤销':'有效'}</span>{!d.revoked&&<button onClick={()=>{if(confirm('确定撤销此设备？'))run(async()=>{await api('/devices/'+d.id,'DELETE');reload()})}}>撤销</button>}</div>)}</section></>;
}

export function RemoteSetup({status,run,reload}:{status:any}&Props){
 const[stun,setStun]=useState('');
 useEffect(()=>{if(status?.network){setStun((status.network.stun_urls??[]).join('\n'))}if(status?.portal_url)setPortal(status.portal_url)},[status]);
 const[portal,setPortal]=useState('https://homeai-connect.pintheworld.cn'),[catalog,setCatalog]=useState<any>(null),[application,setApplication]=useState<any>(null),[plan,setPlan]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;let previousStatus='';const poll=()=>api('/remote/application').then(v=>{if(active){setApplication(v);if(v.status==='APPROVED'&&previousStatus!=='APPROVED')reload();previousStatus=v.status}}).catch(()=>{});poll();const timer=setInterval(poll,10000);return()=>{active=false;clearInterval(timer)}},[]);
 const load=()=>run(async()=>{const value=await api('/remote/catalog','POST',{portal_url:portal});setCatalog(value);setPlan(value.plans[0]?.id??'');setMessage('已获取平台开放套餐')});
 return <><section><h2>远程连接</h2><p>平台只协助配对与连接协商。对话和文件由 iPhone 与家庭服务器直接传输，无法直连时不会使用中继。</p><p>{status?.enabled?'远程协商已启用':'远程协商未启用'} · {status?.runtime?.state==='signalling_online'?'平台协商在线':'尚未确认在线'}</p>{status?.enabled&&<button onClick={()=>run(async()=>{await api('/remote/disable','POST');reload()})}>停用远程连接</button>}{status?.configured&&!status?.enabled&&!status?.migration_required&&<button onClick={()=>run(async()=>{await api('/remote/resume','POST');reload()})}>恢复远程连接</button>}{status?.migration_required&&<button onClick={()=>run(async()=>{await api('/remote/migrate','POST');reload()})}>迁移已有绑定</button>}</section><section><h2>STUN 地址发现</h2><p>两种方式选一种即可：申请远程服务，开通后系统自动保存并使用平台下发的地址，无需再填写；或自行填写第三方 STUN 地址。</p><p>{status?.network?.mode==='custom'?'当前使用自行填写的地址。':status?.configured?'当前自动使用平台下发的地址。':'申请远程服务开通后将自动配置。'}</p><details><summary>自行填写 STUN 地址（可选）</summary><p>最多填写两个地址。留空保存可恢复平台自动配置；开通新的远程服务也会自动使用新平台下发的地址。</p><label>第三方 STUN 地址<textarea value={stun} onChange={e=>setStun(e.target.value)} placeholder="stun:你的地址:3478"/></label><button onClick={()=>run(async()=>{const urls=stun.split(/\s+/).filter(Boolean);await api('/remote/stun','PUT',{mode:urls.length?'custom':'platform',stun_urls:urls});setMessage(urls.length?'自定义地址已保存，已有设备重新扫码后生效':'已恢复平台自动配置，已有设备重新扫码后生效');reload()})}>保存地址</button><p>STUN 只负责发现网络地址，仍需协调平台完成配对授权和连接协商。</p></details></section><section><h2>申请远程服务</h2><label>协调平台地址<input type="url" value={portal} onChange={e=>{setPortal(e.target.value);setCatalog(null);setPlan('')}}/></label><p>默认使用 Home AI Connect；也支持兼容协议的第三方协调平台。</p><button onClick={load}>获取开放套餐与客服</button>{message&&<p role="status">{message}</p>}{catalog&&<><label>套餐<select value={plan} onChange={e=>setPlan(e.target.value)}>{catalog.plans.map((p:any)=><option value={p.id} key={p.id}>{p.name} · ¥{(p.price_cents/100).toFixed(2)} · {p.days} 天 · {p.instances} 个实例</option>)}</select></label>{!catalog.plans.length&&<p>平台暂无开放套餐。</p>}{catalog.support?.wechat&&<p>客服微信：{catalog.support.wechat}</p>}{catalog.support?.qq&&<p>客服 QQ：{catalog.support.qq}</p>}{catalog.support?.email&&<p>客服邮箱：{catalog.support.email}</p>}{!catalog.support?.wechat&&!catalog.support?.email&&!catalog.support?.qq&&<p>平台尚未配置客服联系方式，暂不能申请。</p>}<button className="primary" disabled={!plan||(!catalog.support?.wechat&&!catalog.support?.email&&!catalog.support?.qq)||status?.enabled} onClick={()=>run(async()=>{const value=await api('/remote/applications','POST',{portal_url:portal,plan_id:plan});setApplication({...value,status:'WAITING'});setMessage('将申请码发送给客服；开通后家庭端会自动完成绑定')})}>生成连接申请码</button></>}{application?.request_code&&<><p>申请状态：{({WAITING:'等待客服开通',APPROVED:'已开通',EXPIRED:'申请已过期'} as Record<string,string>)[application.status]??application.status}</p><textarea readOnly value={application.request_code} rows={4} aria-label="连接申请码"/><button onClick={()=>run(async()=>{await navigator.clipboard.writeText(application.request_code);setMessage('申请码已复制')})}>复制申请码</button><button onClick={reload}>刷新连接状态</button></>}</section></>;
}
