import {useEffect,useState} from 'react';
import {api} from './api';
import {MemoryIndex} from './MemoryIndex';
export function DataMemory({records,revision,onChanged}:{records:any[];revision:number;onChanged:()=>void}){
 const[members,setMembers]=useState<any[]>([]),[me,setMe]=useState(''),[owner,setOwner]=useState('all'),[candidates,setCandidates]=useState<any[]>([]),[source,setSource]=useState(''),[content,setContent]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;Promise.all([api('/me'),api('/members'),api('/memory/candidates')]).then(([identity,people,pending])=>{if(active){setMe(identity.user_id);setMembers(people);setCandidates(pending)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[revision]);
 const name=(id:string)=>members.find(m=>m.id===id)?.name??'已授权成员';
 const visible=records.filter(r=>owner==='all'||r.owner_id===owner);
 const own=records.filter(r=>r.owner_id===me&&!r.deleted&&r.sensitivity!=='SECRET');
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setError('');try{await work();onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const render=(r:any)=><details key={r.id}><summary>{r.payload.title??r.payload.name??r.payload.content??r.kind}<span> · {name(r.owner_id)} · {r.kind}</span></summary><pre>{JSON.stringify(Object.fromEntries(Object.entries(r.payload).filter(([key])=>key!=='content_base64')),null,2)}</pre>{r.owner_id===me?<><RecordSharing record={r} members={members.filter(m=>m.id!==me)} onChanged={onChanged}/><button disabled={busy} onClick={()=>{if(confirm('删除这条资料及其派生记忆？'))run(async()=>{await api('/data/'+r.id,'DELETE')})}}>删除我的数据</button></>:<p>由该成员共享，只读；对方撤回后将不可见。</p>}</details>;
 return <><section><h2>数据与记忆的可见范围</h2><p>当前账号：{me?name(me):'读取中'}。这里只显示你的资料和成员明确共享给你的资料；手机配对到其他成员时，需要在 iOS 主动共享。管理员身份不会自动获得私人资料权限。</p><label>成员筛选<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">全部已授权成员</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}{m.id===me?'（我）':''}</option>)}</select></label>{error&&<p role="alert">{error}</p>}</section><section><h2>已授权资料</h2>{visible.filter(r=>r.kind!=='memory.fact').map(render)}{!visible.some(r=>r.kind!=='memory.fact')&&<p>此范围暂无可见资料；可能尚未同步或成员尚未共享，并不代表服务端没有数据。</p>}</section><section><h2>已确认记忆</h2><p>同步原始资料不会自动变成长期记忆。记忆需要基于来源提交、确认，之后才会进入该成员的记忆账本与派生索引。</p>{visible.filter(r=>r.kind==='memory.fact').map(render)}{!visible.some(r=>r.kind==='memory.fact')&&<p>此范围暂无已确认或已共享的记忆。</p>}</section>{(owner==='all'||owner===me)&&<><section><h2>我的候选记忆</h2><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/memory/candidates','POST',{source_ids:[source],content});setContent('')})}}><label>记忆来源<select value={source} onChange={e=>setSource(e.target.value)} required><option value="">选择自己的资料</option>{own.map(r=><option key={r.id} value={r.id}>{r.payload.title??r.payload.name??r.kind}</option>)}</select></label><label>需要记住的内容<textarea value={content} onChange={e=>setContent(e.target.value)} required maxLength={20000}/></label><button disabled={busy||!source||!content.trim()}>提交候选记忆</button></form>{candidates.map(c=><div key={c.id}><p>{c.content}</p><button disabled={busy} onClick={()=>run(async()=>{await api('/memory/candidates/'+c.id+'/confirm','POST')})}>确认记住</button><button disabled={busy} onClick={()=>run(async()=>{await api('/memory/candidates/'+c.id+'/reject','POST')})}>拒绝</button></div>)}</section><MemoryIndex revision={revision} onChanged={onChanged}/></>}</>;
}
function RecordSharing({record,members,onChanged}:{record:any;members:any[];onChanged:()=>void}){
 const[ids,setIds]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const load=async()=>{try{const r=await api('/data/'+record.id+'/grants');setIds(r.grantee_ids);setLoaded(true)}catch(e){setError((e as Error).message)}};
 if(record.sensitivity==='SECRET')return <p>秘密资料不能共享。</p>;
 return <details onToggle={e=>{if(e.currentTarget.open&&!loaded)load()}}><summary>共享此条资料／记忆</summary><p>只共享这一条内容，可随时撤回。</p>{error&&<p role="alert">{error}</p>}{loaded&&members.map(m=><div className="row" key={m.id}><span>{m.name}</span><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api('/data/'+record.id+'/grants/'+m.id,ids.includes(m.id)?'DELETE':'PUT');await load();onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{ids.includes(m.id)?'撤回共享':'共享给该成员'}</button></div>)}</details>;
}
