import {useEffect,useState} from 'react';
import {api} from './api';
export function BuiltinServices({onChanged}:{onChanged:()=>void}){
 const[data,setData]=useState<any>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[variants,setVariants]=useState<Record<string,string>>({});
 const load=async()=>{try{setData(await api('/builtins'));setError('')}catch(e){setError((e as Error).message)}};
 useEffect(()=>{load();const timer=setInterval(load,4000);return()=>clearInterval(timer)},[]);
 const statuses:Record<string,string>={not_installed:'未安装',queued:'等待部署',starting:'下载或启动中',ready:'可用',failed:'失败',disabled:'已停用'};
 return <section><h2>内置服务</h2><p>选择后由服务器下载、校验并启动。模型权重只下载到家庭服务器；联网搜索查询会发送给搜索引擎。</p>{data&&!data.worker_online&&<p role="alert">内置部署器未运行。请按 README 在服务器启动 scripts/run_builtin_services.py，页面会保留你的启用申请。</p>}{error&&<p role="alert">{error}</p>}{data?.items.map((item:any)=><div key={item.id}><h3>{item.name} · {statuses[item.status]??item.status}</h3><select value={variants[item.id]??item.variant} onChange={e=>setVariants({...variants,[item.id]:e.target.value})}>{item.variants.map((v:any)=><option key={v.id} value={v.id}>{v.name}{v.bytes?` · 下载 ${(v.bytes/1e9).toFixed(2)} GB`:''}</option>)}</select>{item.error&&<p role="alert">{item.error}</p>}{[true,false].map(enabled=><button key={String(enabled)} disabled={busy} onClick={async()=>{setBusy(true);try{await api('/builtins/'+item.id,'PUT',{variant:variants[item.id]??item.variant,enabled});await load();onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{enabled?'启用／应用选择':'停用'}</button>)}</div>)}</section>
}
export function MCPIntegration({onChanged}:{onChanged:()=>void}){
 const[id,setID]=useState('mcp.custom'),[url,setURL]=useState(''),[token,setToken]=useState(''),[secret,setSecret]=useState<string>(),[catalog,setCatalog]=useState<any>(),[mapping,setMapping]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const manifest=()=>({id,version:'1.0.0',adapter:'mcp',endpoint:url,allowed_hosts:[new URL(url).hostname],capabilities:{},...(secret?{secret_id:secret}:{})});
 async function inspect(){setBusy(true);setError('');setCatalog(undefined);try{let m=manifest();if(token){const value=await api('/secrets','POST',{provider_id:id,value:token});setSecret(value.id);m={...m,secret_id:value.id};setToken('')}setCatalog(await api('/integrations/mcp/inspect','POST',{manifest:m}));setMapping({})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section><h2>接入 MCP</h2><p>支持 Streamable HTTP。stdio 服务需在服务器部署受控桥接器并按 HTTP Provider 登记；此表单仅接受 Streamable HTTP，不从浏览器执行任意命令。读取目录后明确映射能力，模型按现有权限调用。</p><label>接入名称<input value={id} onChange={e=>{setID(e.target.value);setCatalog(undefined);setSecret(undefined)}}/></label><label>MCP 地址<input type="url" value={url} onChange={e=>{setURL(e.target.value);setCatalog(undefined);setSecret(undefined)}}/></label><label>访问令牌（可选）<input type="password" value={token} onChange={e=>setToken(e.target.value)}/></label><button disabled={busy||!url} onClick={inspect}>连接并读取工具目录</button>{error&&<p role="alert">{error}</p>}{catalog&&<><p>工具描述来自第三方；请选择与实际参数和结果契约相符的能力。未映射工具不会开放，目录变化后需重新核对。</p>{catalog.tools.map((tool:any)=><label key={tool.name}>{tool.name}<details><summary>查看参数契约</summary><pre>{JSON.stringify(tool,null,2)}</pre></details><select value={mapping[tool.name]??''} onChange={e=>setMapping({...mapping,[tool.name]:e.target.value})}><option value="">不开放</option>{catalog.capabilities.map((c:string)=><option key={c}>{c}</option>)}</select></label>)}<button disabled={busy||!Object.values(mapping).some(Boolean)} onClick={async()=>{setBusy(true);try{const entries=Object.entries(mapping).filter(([,value])=>value);if(new Set(entries.map(([,v])=>v)).size!==entries.length)throw Error('同一能力只能映射一个工具');await api('/providers/'+id,'PUT',{...manifest(),capabilities:Object.fromEntries(entries.map(([tool,capability])=>[capability,tool])),mcp_catalog_sha256:catalog.catalog_sha256});onChanged();setError('已保存，核对后在 Provider 页面启用。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>保存映射</button></>}</section>
}
export function SkillIntegration({revision,onChanged}:{revision:number;onChanged:()=>void}){
 const[content,setContent]=useState(''),[items,setItems]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;api('/integrations/skills').then(r=>{if(active)setItems(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[revision]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section><h2>接入 Skill</h2><p>导入标准 SKILL.md（含 name、description 头部）。启用后家庭 Agent 按任务使用指令，工具仍经过服务端策略。此入口支持指令型 Skill，不执行附带脚本、安装命令或宿主文件访问；复杂确定性步骤继续使用自动化中的工作流。</p><input type="file" accept=".md,text/markdown" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>16000){setError('Skill 文件超过 16 KB');return}setContent(await file.text())}}/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="粘贴 SKILL.md 内容" maxLength={16000}/><button disabled={busy||!content.trim()} onClick={()=>run(async()=>{await api('/integrations/skills','POST',{content});setContent('')})}>保存 Skill</button>{error&&<p role="alert">{error}</p>}{items.map(item=><div key={item.id}><h3>{item.name} · {item.enabled?'已启用':'已停用'}</h3><p>{item.description}</p>{item.mine&&<><button disabled={busy} onClick={()=>run(()=>api('/integrations/skills/'+item.id+'/'+(item.enabled?'disable':'enable'),'POST'))}>{item.enabled?'停用':'启用'}</button><button disabled={busy} onClick={()=>run(()=>api('/integrations/skills/'+item.id+'/delete','POST'))}>删除</button></>}</div>)}</section>
}
