import {modelConfiguration} from './modelForm';
import {BuiltinServices,MCPIntegration,SkillIntegration} from './Integrations';
import {Members,RemoteSetup} from './ConnectionSetup';
import {Readiness} from './Readiness';
import {NotificationSettings} from './NotificationSettings';
import {BackupSettings} from './BackupSettings';
import {ModelRouting} from './ModelRouting';

import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{House,Box,Cloud,Users,Database,Radio,Bell,FileText,ExternalLink,LogOut,RefreshCw,ShieldCheck,Menu}from'lucide-react';
import{api}from'./api';import'./style.css';
const sections=[['概览',House],['模型与凭据',Box],['Provider',Cloud],['成员与设备',Users],['通知配置',Bell],['备份与恢复',Database],['远程连接',Radio],['审计',FileText]]as const;
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span><div>{children}</div></label>}
function App(){
 const[me,setMe]=useState<any>(null),[loading,setLoading]=useState(true),[section,setSection]=useState('模型与凭据'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[mobile,setMobile]=useState(false),[reauth,setReauth]=useState(false);
 const run=async(fn:()=>Promise<void>)=>{setError('');setNotice('');try{await fn()}catch(e){setError((e as Error).message)}};
 const reload=()=>setRevision(v=>v+1);
 useEffect(()=>{api('/me').then(setMe).catch(()=>{}).finally(()=>setLoading(false))},[]);
 if(loading)return <main className="login"><p>正在连接家庭服务器…</p></main>;
 if(!me)return <Auth onLogin={async()=>setMe(await api('/me'))}/>;
 return <div className="shell"><aside className={mobile?'open':''}><a className="brand" href="#"><House size={28}/><b>Home AI</b></a><nav>{sections.map(([title,Icon])=><button key={title} className={section===title?'selected':''} onClick={()=>{setSection(title);setMobile(false);setError('');setNotice('')}}><Icon size={20}/>{title}</button>)}</nav><a className="attribution" href="https://github.com/MR-MaoJiu/home-ai-os" target="_blank" rel="noreferrer">基于 Home AI OS <ExternalLink size={14}/></a></aside><main><header><div><button aria-label="打开导航" className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu/></button><h1>{section}</h1><p>{section==='模型与凭据'?'所有凭据仅保存在你的家庭服务器。':'管理家庭服务器、能力与设备。'}</p></div><div className="header-actions"><button onClick={()=>setReauth(!reauth)}>重新验证</button><button onClick={()=>run(async()=>{await api('/browser/logout','POST');setMe(null)})}><LogOut size={16}/>退出登录</button></div></header>{error&&<div className="message error" role="alert">{error}</div>}{notice&&<div className="message" role="status">{notice}</div>}
 {reauth&&<section><h2>确认敏感操作身份</h2><form className="inline" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/browser/reauth','POST',{code:f.get('code')});setReauth(false);setNotice('验证成功；登录有效期内无需重复输入动态码')})}}><input name="code" autoComplete="one-time-code" placeholder="动态验证码" required pattern="[0-9]{6}"/><button className="primary">确认身份</button></form></section>}
 <Panel key={section} section={section} revision={revision} run={run} reload={reload} notify={setNotice}/><footer>Home AI OS · 开发版本 · 家庭数据默认本地处理</footer></main></div>
}
function Auth({onLogin}:{onLogin:()=>Promise<void>}){
 const[setup,setSetup]=useState(false),[secret,setSecret]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{
  if(secret){await api('/browser/totp/confirm','POST',{code:form.get('code')});await onLogin()}
  else if(setup){const r=await api('/browser/setup','POST',{ticket:form.get('ticket'),username:form.get('username'),password:form.get('password')});setSecret(r.secret)}
  else{await api('/browser/login','POST',{username:form.get('username'),code:form.get('code')});await onLogin()}
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="login"><div className="login-brand"><House size={30}/><b>Home AI</b></div><section className="auth-panel"><ShieldCheck className="accent" size={36}/><h1>{secret?'绑定验证器':setup?'初始化管理账户':'欢迎回家'}</h1><p>{secret?'将此密钥导入 iOS 设置中的“管理端动态码”或标准验证器，再输入当前验证码。请安全保存，页面关闭后不会回显。':'登录家庭服务器，管理配置与设备。'}</p>{error&&<div className="message error" role="alert">{error}</div>}<form onSubmit={submit}>{secret?<><code className="secret">{secret}</code><label>动态验证码<input name="code" inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}"/></label></>:<>{setup&&<label>本机初始化凭据<input name="ticket" type="password" required autoComplete="off"/></label>}<label>用户名<input name="username" required autoComplete="username"/></label>{setup&&<label>恢复备用密码<input name="password" type="password" minLength={12} required autoComplete="new-password"/></label>}{!setup&&<label>动态验证码<input name="code" inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}"/></label>}</>}<button className="primary" disabled={busy}>{busy?'正在验证…':secret?'确认绑定':setup?'创建账户':'安全登录'}</button></form>{!secret&&<button className="link" onClick={()=>setSetup(!setup)}>{setup?'已有账户，返回登录':'首次部署？使用本机凭据初始化'}</button>}</section><a className="attribution" href="https://github.com/MR-MaoJiu/home-ai-os">基于 Home AI OS <ExternalLink size={14}/></a></main>
}
type Props={section:string,revision:number,run:(f:()=>Promise<void>)=>Promise<void>,reload:()=>void,notify:(s:string)=>void};
function Panel({section,revision,run,reload,notify}:Props){
 const[data,setData]=useState<any>(null),[secondary,setSecondary]=useState<any>(null),[busy,setBusy]=useState(false);
 const paths:Record<string,string>={'概览':'/manage/overview','模型与凭据':'/providers','Provider':'/providers','成员与设备':'/members','备份与恢复':'/manage/backups','远程连接':'/remote/status','审计':'/activity'};
 useEffect(()=>{if(!paths[section])return;let active=true;setBusy(true);run(async()=>{const [value,devices]=await Promise.all([api(paths[section]),section==='成员与设备'?api('/devices'):Promise.resolve(null)]);if(active){setData(value);setSecondary(devices)}}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[section,revision]);
 const mutate=(path:string,method='POST',body?:unknown)=>run(async()=>{await api(path,method,body);notify('操作已保存');reload()});
 if(section==='模型与凭据')return <><ModelRouting providers={data??[]} revision={revision} onVerified={(id,healthy)=>setData((previous:any[])=>previous?.map(p=>p.id===id?{...p,health:healthy?'online':'unavailable'}:p))}/><BuiltinServices onChanged={reload}/><MCPIntegration onChanged={reload}/><SkillIntegration revision={revision} onChanged={reload}/><div className="columns"><section><h2>接入模型</h2><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run(async()=>{const manifest:any=modelConfiguration(form);const id=manifest.id;await api('/providers/'+id,'PUT',manifest);const key=String(form.get('key')??'').trim();if(key){const secret=await api('/secrets','POST',{provider_id:id,value:key});manifest.secret_id=secret.id;await api('/providers/'+id,'PUT',manifest)}notify('配置已保存，默认停用。请核对后在 Provider 页面启用。');reload()})}}><Field label="Provider ID"><input name="id" placeholder="例如：local.llama" required minLength={2} maxLength={81} pattern={'[A-Za-z][A-Za-z0-9_.\\-]{1,80}'}/><small>英文大小写均可，保存时统一为小写；可使用数字、点、下划线或连字符。</small></Field><Field label="接口地址"><input name="endpoint" type="url" placeholder="http://127.0.0.1:8080/v1" required/><small>填写模型服务的 Base URL；本地模型使用 localhost 或局域网 IP，公网接口请选择云端。</small></Field><Field label="模型名称"><input name="model" placeholder="填写服务中实际可用的模型" required/></Field><Field label="部署类型"><div className="radios"><label><input name="type" type="radio" value="local" defaultChecked/>本地</label><label><input name="type" type="radio" value="cloud"/>云端</label></div></Field><Field label="API Key"><input name="key" type="password" autoComplete="new-password" placeholder="本地无密钥服务可留空"/><small>凭据将加密保存，不会回显。</small></Field><div className="form-action"><button className="primary">保存配置</button></div></form></section><section className="help"><h2>配置说明</h2><h3>本地优先</h3><p>推荐优先接入运行在家庭服务器或局域网中的模型服务。</p><hr/><h3>凭据安全</h3><p>API Key 等敏感信息加密保存在家庭服务器，页面不会读取已保存的明文。</p><hr/><h3>云端接入</h3><p>配置云服务不等于授权个人数据上云。调用仍须经过隐私策略检查。</p></section></div><section><h2>已配置模型</h2><Providers data={data} mutate={mutate}/></section></>;
 if(section==='通知配置')return <NotificationSettings/>;
 if(busy&&!data)return <section><p className="empty">正在加载…</p></section>;
 if(section==='Provider')return <section><p>服务端统一调用已启用的能力，并校验权限与隐私策略。在线表示服务可达。</p><div className="section-title"><h2>能力提供方</h2><button onClick={reload}><RefreshCw size={16}/>刷新</button></div><Providers data={data} mutate={mutate}/></section>;
 if(section==='概览')return <><section><h2>家庭服务状态</h2><div className="summary">{[['有效设备',data?.devices]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v??'—'}</strong></div>)}</div><p>当前环境：{data?.environment??'—'}</p></section><Readiness/></>;
 if(section==='成员与设备')return <Members members={data??[]} devices={secondary??[]} run={run} reload={reload}/>;
 if(section==='备份与恢复')return <BackupSettings archives={data??[]} onChanged={reload}/>;
 if(section==='远程连接')return <RemoteSetup status={data} run={run} reload={reload}/>;

 return <><section><h2>操作记录</h2><Rows rows={data?.entries} keys={['action','resource_id','created_at']}/></section><section><h2>云端披露</h2><Rows rows={data?.disclosures} keys={['provider','bytes_sent','status']}/></section></>;
}
function Empty({text}:{text:string}){return <div className="empty"><Box size={32}/><p>{text}</p></div>}
const labels:Record<string,string>={name:'名称',role:'角色',id:'标识',status:'状态',error:'错误',created_at:'时间',action:'操作',resource_id:'关联资源',bytes:'大小（字节）',modified_at:'更新时间',bytes_sent:'发送字节数',provider:'提供方'}; const display=(value:unknown)=>({infrastructure_owner:'家庭管理员',adult:'成年成员',SUCCEEDED:'成功',FAILED:'失败',RECEIVED:'已接收',EXECUTING:'执行中',AWAITING_APPROVAL:'等待审批',CANCELED:'已取消',degraded:'待验证',unavailable:'暂时不可用',online:'最近调用正常',offline:'离线',healthy:'正常',ready:'服务可达'}[String(value)]??String(value??'—'));
function Rows({rows,keys}:{rows:any[],keys:string[]}){return rows?.length?<div className="table-scroll"><table><thead><tr>{keys.map(k=><th key={k}>{labels[k]??k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k}>{display(r[k])}</td>)}</tr>)}</tbody></table></div>:<Empty text="暂无记录"/>}
function Providers({data,mutate}:{data:any[],mutate:(path:string,method?:string,body?:unknown)=>void}){return <div className="table-scroll"><table><thead><tr><th>名称</th><th>类型</th><th>状态</th><th>操作</th></tr></thead><tbody>{data?.map(p=><tr key={p.id}><td><b>{p.id}</b><small>{p.manifest.model??p.manifest.adapter}</small></td><td>{p.manifest.cloud?'云端':'本地'}</td><td>{p.enabled?'已启用':'已停用'} · {display(p.health)}</td><td><button onClick={()=>mutate('/providers/'+p.id+'/'+(p.enabled?'disable':'enable'))}>{p.enabled?'停用':'启用'}</button><button onClick={()=>mutate('/providers/'+p.id+'/rollback')}>回滚配置</button></td></tr>)}</tbody></table>{!data?.length&&<Empty text="尚未配置模型"/>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
