import {MemoryIndex} from './MemoryIndex';
import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{House,Box,Cloud,Users,Database,ClipboardCheck,Settings,Radio,FileText,ExternalLink,LogOut,RefreshCw,ShieldCheck,Menu}from'lucide-react';
import{api}from'./api';import'./style.css';
const sections=[['概览',House],['模型与凭据',Box],['Provider',Cloud],['成员与设备',Users],['数据与记忆',Database],['任务与审批',ClipboardCheck],['自动化',Settings],['备份与恢复',Database],['远程连接',Radio],['审计',FileText]]as const;
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span><div>{children}</div></label>}
function App(){
 const[me,setMe]=useState<any>(null),[loading,setLoading]=useState(true),[section,setSection]=useState('模型与凭据'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[mobile,setMobile]=useState(false),[reauth,setReauth]=useState(false);
 const run=async(fn:()=>Promise<void>)=>{setError('');setNotice('');try{await fn()}catch(e){setError((e as Error).message)}};
 const reload=()=>setRevision(v=>v+1);
 useEffect(()=>{api('/me').then(setMe).catch(()=>{}).finally(()=>setLoading(false))},[]);
 if(loading)return <main className="login"><p>正在连接家庭服务器…</p></main>;
 if(!me)return <Auth onLogin={async()=>setMe(await api('/me'))}/>;
 return <div className="shell"><aside className={mobile?'open':''}><a className="brand" href="#"><House size={28}/><b>Home AI</b></a><nav>{sections.map(([title,Icon])=><button key={title} className={section===title?'selected':''} onClick={()=>{setSection(title);setMobile(false);setError('');setNotice('')}}><Icon size={20}/>{title}</button>)}</nav><a className="attribution" href="https://github.com/MR-MaoJiu/home-ai-os" target="_blank" rel="noreferrer">基于 Home AI OS <ExternalLink size={14}/></a></aside><main><header><div><button aria-label="打开导航" className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu/></button><h1>{section}</h1><p>{section==='模型与凭据'?'所有凭据仅保存在你的家庭服务器。':'管理你的家庭 AI，数据权限由你决定。'}</p></div><div className="header-actions"><button onClick={()=>setReauth(!reauth)}>重新验证</button><button onClick={()=>run(async()=>{await api('/browser/logout','POST');setMe(null)})}><LogOut size={16}/>退出登录</button></div></header>{error&&<div className="message error" role="alert">{error}</div>}{notice&&<div className="message" role="status">{notice}</div>}
 {reauth&&<section><h2>确认敏感操作身份</h2><form className="inline" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api('/browser/reauth','POST',{password:f.get('password'),code:f.get('code')});setReauth(false);setNotice('已重新验证，敏感操作权限有效 5 分钟')})}}><input name="password" type="password" autoComplete="current-password" placeholder="账户密码" required/><input name="code" autoComplete="one-time-code" placeholder="动态验证码" required pattern="[0-9]{6}"/><button className="primary">确认身份</button></form></section>}
 <Panel key={section} section={section} revision={revision} run={run} reload={reload} notify={setNotice}/><footer>Home AI OS · 开发版本 · 家庭数据默认本地处理</footer></main></div>
}
function Auth({onLogin}:{onLogin:()=>Promise<void>}){
 const[setup,setSetup]=useState(false),[secret,setSecret]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{
  if(secret){await api('/browser/totp/confirm','POST',{code:form.get('code')});await onLogin()}
  else if(setup){const r=await api('/browser/setup','POST',{ticket:form.get('ticket'),username:form.get('username'),password:form.get('password')});setSecret(r.secret)}
  else{await api('/browser/login','POST',{username:form.get('username'),password:form.get('password'),code:form.get('code')});await onLogin()}
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="login"><div className="login-brand"><House size={30}/><b>Home AI</b></div><section className="auth-panel"><ShieldCheck className="accent" size={36}/><h1>{secret?'绑定验证器':setup?'初始化管理账户':'欢迎回家'}</h1><p>{secret?'将密钥添加到你的验证器，再输入当前验证码。':'登录你自己的家庭服务器，继续管理数据与设备。'}</p>{error&&<div className="message error" role="alert">{error}</div>}<form onSubmit={submit}>{secret?<><code className="secret">{secret}</code><label>动态验证码<input name="code" inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}"/></label></>:<>{setup&&<label>本机初始化凭据<input name="ticket" type="password" required autoComplete="off"/></label>}<label>用户名<input name="username" required autoComplete="username"/></label><label>密码<input name="password" type="password" minLength={setup?12:1} required autoComplete={setup?'new-password':'current-password'}/></label>{!setup&&<label>动态验证码<input name="code" inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}"/></label>}</>}<button className="primary" disabled={busy}>{busy?'正在验证…':secret?'确认绑定':setup?'创建账户':'安全登录'}</button></form>{!secret&&<button className="link" onClick={()=>setSetup(!setup)}>{setup?'已有账户，返回登录':'首次部署？使用本机凭据初始化'}</button>}</section><a className="attribution" href="https://github.com/MR-MaoJiu/home-ai-os">基于 Home AI OS <ExternalLink size={14}/></a></main>
}
type Props={section:string,revision:number,run:(f:()=>Promise<void>)=>Promise<void>,reload:()=>void,notify:(s:string)=>void};
function Panel({section,revision,run,reload,notify}:Props){
 const[data,setData]=useState<any>(null),[secondary,setSecondary]=useState<any>(null),[busy,setBusy]=useState(false);
 const paths:Record<string,string>={'概览':'/manage/overview','模型与凭据':'/providers','Provider':'/providers','成员与设备':'/members','数据与记忆':'/data','任务与审批':'/manage/tasks','自动化':'/automations','备份与恢复':'/manage/backups','远程连接':'/remote/status','审计':'/activity'};
 useEffect(()=>{let active=true;setBusy(true);run(async()=>{const value=await api(paths[section]);if(active)setData(value);if(section==='成员与设备'||section==='任务与审批'){const second=await api(section==='成员与设备'?'/devices':'/approvals');if(active)setSecondary(second)}}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[section,revision]);
 const mutate=(path:string,method='POST',body?:unknown)=>run(async()=>{await api(path,method,body);notify('操作已保存');reload()});
 if(section==='模型与凭据')return <><div className="columns"><section><h2>接入模型</h2><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const id=String(form.get('id'));const endpoint=String(form.get('endpoint'));run(async()=>{const manifest:any={id,version:'1.0.0',adapter:'openai',endpoint,model:form.get('model'),cloud:form.get('type')==='cloud',capabilities:{'model.generate@v1':'chat'},allowed_hosts:[new URL(endpoint).hostname]};await api('/providers/'+id,'PUT',manifest);const key=String(form.get('key')??'');if(key){const secret=await api('/secrets','POST',{provider_id:id,value:key});manifest.secret_id=secret.id;await api('/providers/'+id,'PUT',manifest)}notify('配置已保存，默认停用。请核对后在 Provider 页面启用。');reload()})}}><Field label="Provider ID"><input name="id" placeholder="例如：local.llama" required pattern="[a-z][a-z0-9_.-]+"/><small>使用小写英文、数字、点、下划线或连字符。</small></Field><Field label="接口地址"><input name="endpoint" type="url" placeholder="http://127.0.0.1:8080/v1" required/><small>填写模型服务的 Base URL。</small></Field><Field label="模型名称"><input name="model" placeholder="填写服务中实际可用的模型" required/></Field><Field label="部署类型"><div className="radios"><label><input name="type" type="radio" value="local" defaultChecked/>本地</label><label><input name="type" type="radio" value="cloud"/>云端</label></div></Field><Field label="API Key"><input name="key" type="password" autoComplete="new-password" placeholder="本地无密钥服务可留空"/><small>凭据将加密保存，不会回显。</small></Field><div className="form-action"><button className="primary">保存配置</button></div></form></section><section className="help"><h2>配置说明</h2><h3>本地优先</h3><p>推荐优先接入运行在家庭服务器或局域网中的模型服务。</p><hr/><h3>凭据安全</h3><p>API Key 等敏感信息加密保存在家庭服务器，页面不会读取已保存的明文。</p><hr/><h3>云端接入</h3><p>配置云服务不等于授权个人数据上云。调用仍须经过隐私策略检查。</p></section></div><section><h2>已配置模型</h2><Providers data={data} mutate={mutate}/></section></>;
 if(busy&&!data)return <section><p className="empty">正在加载…</p></section>;
 if(section==='Provider')return <section><div className="section-title"><h2>能力提供方</h2><button onClick={reload}><RefreshCw size={16}/>刷新</button></div><Providers data={data} mutate={mutate}/></section>;
 if(section==='概览')return <><section><h2>家庭服务状态</h2><div className="summary">{[['可见数据',data?.records],['我的任务',data?.tasks],['有效设备',data?.devices]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v??'—'}</strong></div>)}</div><p>当前环境：{data?.environment??'—'}</p></section><section><h2>部署检查</h2><button onClick={()=>run(async()=>{const r=await api('/manage/readiness');notify(`数据库：${r.database?'已连接':'不可用'}；主密钥：${r.master_key_loaded?'已加载':'未加载'}；生产隔离：${r.production_sandbox_verified?'已验证':'尚未验收'}`)})}>检查部署条件</button></section></>;
 if(section==='成员与设备')return <><section><h2>家庭成员</h2><Rows rows={data} keys={['name','role']}/><form className="inline" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run(async()=>{const r=await api('/members/invite','POST',{name:form.get('name')});notify(`一次性配对码（5 分钟有效）：${r.pairing_token}`);reload()})}}><input name="name" placeholder="新成员名称" required/><button className="primary">邀请成员</button></form></section><section><h2>我的设备</h2>{secondary?.map((d:any)=><div className="row" key={d.id}><span>{d.name}</span><span>{d.revoked?'已撤销':'有效'}</span>{!d.revoked&&<button onClick={()=>{if(confirm('撤销后该设备无法继续访问，确定吗？'))mutate('/devices/'+d.id,'DELETE')}}>撤销</button>}</div>)}</section></>;
 if(section==='数据与记忆')return <><MemoryIndex revision={revision} onChanged={reload}/><section><h2>已授权数据</h2>{data?.records?.length?data.records.map((r:any)=><details key={r.id}><summary>{r.payload.title??r.payload.name??r.kind}<span>{r.sensitivity}</span></summary><pre>{JSON.stringify(r.payload,null,2)}</pre><button onClick={()=>{if(confirm('确认删除这条数据及其派生记忆？'))mutate('/data/'+r.id,'DELETE')}}>删除数据</button></details>):<Empty text="暂无已授权数据"/>}</section></>;
 if(section==='任务与审批')return <><section><h2>等待确认</h2>{secondary?.length?secondary.map((a:any)=><div className="approval" key={a.id}><b>{a.capability}</b><pre>{JSON.stringify(a.arguments,null,2)}</pre><button onClick={()=>mutate('/approvals/'+a.id,'POST',{decision:'REJECTED'})}>拒绝</button><button className="primary" onClick={()=>mutate('/approvals/'+a.id,'POST',{decision:'APPROVED'})}>确认执行</button></div>):<Empty text="没有待确认操作"/>}</section><section><h2>最近任务</h2><Rows rows={data} keys={['id','status','error']}/></section></>;
 if(section==='自动化')return <section><h2>定时提醒</h2><form className="inline" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);mutate('/automations','POST',{name:form.get('title'),cron:form.get('cron'),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,enabled:true,skill:{name:form.get('title'),steps:[{capability:'reminder.create@v1',arguments:{title:form.get('title')}}]}})}}><input name="title" placeholder="提醒内容" required/><input name="cron" placeholder="0 8 * * *" required/><button className="primary">创建</button></form>{data?.map((a:any)=><div className="row" key={a.id}><b>{a.name}</b><span>{a.cron}</span><span>{a.enabled?'已启用':'已停用'}</span>{a.enabled&&<button onClick={()=>mutate('/automations/'+a.id,'DELETE')}>停用</button>}</div>)}</section>;
 if(section==='备份与恢复')return <section><h2>加密备份</h2><p>恢复必须在家庭服务器本机操作，避免远程误覆盖数据。此处展示已有加密归档。</p><Rows rows={data} keys={['name','bytes','modified_at']}/></section>;
 if(section==='远程连接')return <><section><h2>Home AI Connect</h2><p>可选托管远程服务。本地功能不需要平台注册或付费。</p><p>绑定状态：{data?.configured?'已配置':'尚未绑定'} · 隧道状态：{({disabled:'已停用',agent_not_running:'连接程序未运行',lease_active:'租约有效，外网连通需另行验证',disconnected:'连接中断',stale:'连接程序状态已过期'} as Record<string,string>)[data?.runtime?.state]??'未检查'}</p>{data?.url&&<p><a href={data.url} target="_blank" rel="noreferrer">{data.url}</a></p>}<button onClick={()=>run(async()=>{const r=await api('/remote/request-code');notify('请在连接平台粘贴此申请码：'+r.request_code)})}>生成连接申请码</button>{data?.enabled&&<button onClick={()=>mutate('/remote/disable')}>关闭远程连接</button>}</section><section><h2>确认平台绑定</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate('/remote/bind','POST',{portal_url:f.get('portal'),binding_code:f.get('code'),local_https_port:Number(f.get('port'))})}}><Field label="平台地址"><input name="portal" type="url" defaultValue="https://homeai-connect.pintheworld.cn" required/></Field><Field label="绑定码"><input name="code" autoComplete="off" required/></Field><Field label="本地 HTTPS 端口"><input name="port" type="number" defaultValue="58443" required min="1024" max="65535"/></Field><button className="primary">确认绑定</button></form><p>绑定后需运行远程连接程序。证书未签发或网络不可用时，系统不会将其显示为已连通。</p></section></>;

 return <><section><h2>操作记录</h2><Rows rows={data?.entries} keys={['action','resource_id','created_at']}/></section><section><h2>云端披露</h2><Rows rows={data?.disclosures} keys={['provider','bytes_sent','status']}/></section></>;
}
function Empty({text}:{text:string}){return <div className="empty"><Box size={32}/><p>{text}</p></div>}
const labels:Record<string,string>={name:'名称',role:'角色',id:'标识',status:'状态',error:'错误',created_at:'时间',action:'操作',resource_id:'关联资源',bytes:'大小（字节）',modified_at:'更新时间',bytes_sent:'发送字节数',provider:'提供方'}; const display=(value:unknown)=>({infrastructure_owner:'家庭管理员',adult:'成年成员',SUCCEEDED:'成功',FAILED:'失败',RECEIVED:'已接收',EXECUTING:'执行中',AWAITING_APPROVAL:'等待审批',CANCELED:'已取消',degraded:'待验证',offline:'离线',healthy:'正常'}[String(value)]??String(value??'—'));
function Rows({rows,keys}:{rows:any[],keys:string[]}){return rows?.length?<div className="table-scroll"><table><thead><tr>{keys.map(k=><th key={k}>{labels[k]??k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k}>{display(r[k])}</td>)}</tr>)}</tbody></table></div>:<Empty text="暂无记录"/>}
function Providers({data,mutate}:{data:any[],mutate:(path:string,method?:string,body?:unknown)=>void}){return <div className="table-scroll"><table><thead><tr><th>名称</th><th>类型</th><th>状态</th><th>操作</th></tr></thead><tbody>{data?.map(p=><tr key={p.id}><td><b>{p.id}</b><small>{p.manifest.model??p.manifest.adapter}</small></td><td>{p.manifest.cloud?'云端':'本地'}</td><td>{p.enabled?'已启用':'已停用'} · {display(p.health)}</td><td><button onClick={()=>mutate('/providers/'+p.id+'/'+(p.enabled?'disable':'enable'))}>{p.enabled?'停用':'启用'}</button><button onClick={()=>mutate('/providers/'+p.id+'/rollback')}>回滚配置</button></td></tr>)}</tbody></table>{!data?.length&&<Empty text="尚未配置模型"/>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
